require pysvn 1.8 for subversion 1.9
$ pysvn-workbench
PySVN WorkBench starting
Traceback (most recent call last):
  File "/usr/share/pysvn-workbench/wb_main.py", line 59, in <module>
    import wb_app
  File "/usr/share/pysvn-workbench/wb_app.py", line 65, in <module>
    import wb_frame
  File "/usr/share/pysvn-workbench/wb_frame.py", line 18, in <module>
    import wb_tree_panel
  File "/usr/share/pysvn-workbench/wb_tree_panel.py", line 22, in <module>
    import wb_dialogs
  File "/usr/share/pysvn-workbench/wb_dialogs.py", line 16, in <module>
    import wb_subversion_utils
  File "/usr/share/pysvn-workbench/wb_subversion_utils.py", line 187, in <module>
    wc_notify_action_map[ pysvn.wc_notify_action.failed_locked ] = "failed_locked"
AttributeError: failed_locked